version: '3.8'

services:
  mcp-validator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reports:/app/reports
    environment:
      - MCP_SERVER_URL=${MCP_SERVER_URL:-http://mcp-server:8080}
    command: "--url ${MCP_SERVER_URL:-http://mcp-server:8080} --report /app/reports/mcp-compliance-report.html"
    networks:
      - mcp-network

  # Example of how to include a test server (commented out)
  # mcp-server:
  #   image: example/mcp-server:latest
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - mcp-network

networks:
  mcp-network:
    driver: bridge 